test cases for profile
cs130-w21/7 pull request #98
Opened 2021-03-03 08:15 UTC by LeroyS1

Added test cases to test profile APIs on the backend side

2021-03-03 11:37 UTC, ngducn approved these changes

2021-03-03 16:57 UTC, ngducn requested changes

2021-03-03 16:57 UTC, ngducn commented on backend/tests/test_profile.py
> +        "cuisin":"Vietnamese",
Is "cuisin" supposed to be "cuisine"?

2021-03-03 20:06 UTC, nguyenhoaihuy commented on backend/tests/test_profile.py
> +        "cuisin":"Vietnamese",
I can change it

2021-03-04 01:32 UTC, ngducn approved these changes

2021-03-04 05:40 UTC, merged